kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: pddstudio/iw4x-docker
      tags: latest
      dockerfile: docker/Dockerfile.drone
      build_args:
        - IW4X_PORT=28960
        - IW4X_CONFIG=./config/server.cfg
        - IW4X_MODS=./data/mods
        - IW4X_ARGS="-dedicated +set net_port 28960 +exec server.cfg +party_enable 0 +map_rotate +set fs_game \"mods/bots\""
