version: "3.7"

networks:
  netstack:
    external: true

services:
  iw4x-server:
    build:
      context: "./docker/"
      args:
        # You can change these matching the ids of your current user, except if you are root.
        - USER_ID=1000
        - GROUP_ID=1000
    image: "pddstudio/iw4x-docker:latest"
    container_name: iw4x-docker
    # Will auto-restart your server if it crashes.
    restart: always
    volumes:
      # Copy the whole dedicated server into iw4x-dedicated/data/ and make sure the files are owned by the values of ${USER_ID} and ${GROUP_ID}
      - "./data/:/iw4x/server/"
    networks:
      - netstack
    ports:
      - "28960:28960/udp"
      - "28960:28960"
    labels:
      - "traefik.docker.network=private"
      - "traefik.enable=true"
      - "traefik.port=28960"
      - "traefik.frontend.rule=Host:iw4x.pddstudio.io"
