version: "3.7"

networks:
  netstack:
    external: true

services:
  iw4x-server:
    build:
      context: "./docker/"
      args:
        # You can change these matching the ids of your current user, except if you are root.
        - USER_ID=1000
        - GROUP_ID=1000
        - ARG_IW4X_PORT=${IW4X_PORT}
        - ARG_IW4X_ARGS=${IW4X_ARGS}
        - ARG_IW4X_CONFIG=${IW4X_CONFIG}
    image: "pddstudio/iw4x-docker:latest"
    container_name: iw4x-docker
    # Will auto-restart your server if it crashes.
    restart: always
    volumes:
      - type: bind
        source: ./data/client
        target: /iw4x/server
      - "${IW4X_CONFIG}:/iw4x/server/userraw/server.cfg"
      - "${IW4X_MODS}:/iw4x/server/mods"
    env_file: .env
    networks:
      - netstack
    ports:
      - "${IW4X_PORT}:${IW4X_PORT}/udp"
      - "${IW4X_PORT}:${IW4X_PORT}"
    labels:
      - "traefik.docker.network=private"
      - "traefik.enable=true"
      - "traefik.port=${IW4X_PORT}"
      - "traefik.frontend.rule=Host:iw4x.pddstudio.io"
