version: "3.7"

services:

  iw4x-server:
    image: "iw4x-docker:latest"
    build:
      context: "./docker/"
    container_name: iw4x-docker
    # Will auto-restart your server if it crashes.
    restart: always
    volumes:
      - "./data/server:/iw4x/server"
      - "./config/server.cfg:/iw4x/server/userraw/server.cfg"
    env_file: .env
    ports:
      - "28960:28960/udp"
      - "28960:28960"
